### ISSUE TITLE
Spacing between title and description

### ISSUE THREAD

**Issue by elimae17** [JulianPrieber/llc-default#5]
Hi,

I really like your theming system, it's straight forward and easy to edit!

For our company, I changed the default theme a bit; some custom fonts, different colors and sizes, and so on. However, I ran into a problem. We want to use the description of the website as a subtitle, that is, a one-liner with little text. Therefore I want to reduce the space between the title and the description. I noticed that in the skeleton-auto.css file there is no special section for the description, so using the browser's inspector I found out that the spacing is controlled by the .description_parent class. So I added something like the following to the skeleton_auto.css file:

```
  .description-parent {
    margin-bottom: 50px !important;;
    font-size: 30px;
    line-height: 1.2em;
    padding-bottom: 0px !important;
}
```

But that didn't produce the desired result, there was still some spacing. I then noticed that the problem was caused by this inline CSS rule that uses the universal selector (*) and seems to override my CSS in some way:
```
.description-parent * {
 margin-bottom: 0em;
}
```
When I remove the asterisk it works:
![Screenshot 1](https://github.com/LinkStackOrg/linkstack-default-theme/assets/106697497/e4d217c0-b1a6-45ae-9012-acc5399ddb4a)
![Screenshot 2](https://github.com/LinkStackOrg/linkstack-default-theme/assets/106697497/f859ce7b-5e30-4049-aa97-51bbf3062d2d)

It seems that this inline styling comes from the /resources/views/littlelink.blade.php file. I'm not an CSS expert, so there might be a better way, but the only one I found to reduce the spacing was to remove the  <style> tag from that file. But this change is reverted after every update I guess?

I think it would be great if there was the possibility to change the descriptions syling directly in the thme's CSS files without any style tags coming from the application itself overriding it. If there is already, I would be grateful for someone pointing it out to me.

Thanks again for this awesome software!

**Comment by JulianPrieber** [comment]
![Code_9N1dBzgcoU](https://github.com/LinkStackOrg/linkstack-default-theme/assets/60265788/3f4aca91-5a15-4c25-afe8-a34179cfb4db)

I added some inline styling to reduce the spacing between the title and description. I decided for this approach to not have to edit every single theme.

You can simply overwrite this styling by adding the `.description-parent * {}` class to your theme. You can set the margin-bottom to either 0 or a negative value to reduce spacing even further.

**Comment by elimae17** [comment]
Thanks for the info!

I ended up using the following code which worked for me:

```
  .description-parent {
    font-size: 30px;
    line-height: 1.2em;
    padding-bottom: 50px !important;
   }

  .description-parent * {
    margin-bottom: 0em !important;
   }
```
